const reduxActionTypes = {
    SET_POSTS: 'SET_POSTS',
    GET_MORE_POSTS: 'GET_MORE_POSTS',
    SET_POSTS_HAS_MORE: 'SET_POSTS_HAS_MORE',
    UPDATE_POST:'UPDATE_POST',
    //Todo
    SET_TODOS: 'SET_TODOS',
    GET_MORE_TODOS: 'GET_MORE_TODOS',
    SET_TODOS_HAS_MORE: 'SET_TODOS_HAS_MORE',
    SET_TODO_HAS_MORE:"SET_TODO_HAS_MORE",
    UPDATE_TODO:'UPDATE_TODO',
}

export default reduxActionTypes